### ISSUE TITLE
"send2cgeo" script conflicts with "Geocaching.com + Project-GC" script

### ISSUE THREAD

**Issue by Robbie711** [cgeo/send2cgeo#89] opened 2020-02-16 01:36 UTC
When Geocaching.com + Project-GC script and send2cgeo are both running in Tampermonkey, two problems (more mybe unnoticed) 

1. "Add to List" does not function

2. Map doesn't appear (through "View Larger Map" does work.

See Geocaching.com + Project-GC here:
https://greasyfork.org/en/scripts/9713-geocaching-com-project-gc

**Comment by capoaira** [comment] 2020-02-16 01:53
This is a duplicate of #66, #81, #82 and fixed with  #86. It comes in the next release.

**Comment by Robbie711** [comment] 2020-02-16 06:28
Thanks! I'm new to github (and find it a little daunting). So all I need to do is update the script in FF? How will I know when it's released. Thanks again for doing the script -- and the fixes!

**Comment by capoaira** [comment] 2020-02-16 06:55
Yes, Github is a bit confusing for the first time.
You get the update automatically, so you have only to wait until the next release is ready.

**Closed** 2020-02-17 20:36 UTC
Labels: Duplicate
