### ISSUE TITLE
conflicts with project-gc script

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/send2cgeo#19] opened 2015-08-03 18:21 UTC
From a facebook discussion: If both our script and the one from project-gc are installed, then the send2 button is sometimes missing. I can reproduce it.

**Comment by Bananeweizen** [comment] 2015-08-03 18:58
I've been looking into the sources of both scripts and I don't understand the issue. From what I can see we are using rather little identifying parts of the page to add our HTML: $('#Download p:last'). And I don't see where this would be modified in the project-gc script. And I have no clue how to debug such stuff...

**Comment by Lineflyer** [comment] 2015-08-03 19:44
@Bananeweizen 
I don't seem to have this issue.
What are you using and in which sequence you start the scripts in Greasemonkey/Tampermonkey?

Me:
Firefox 39.0
Greasemonkey 2.2
send2cgeo 0.32
Project GC 1.45
GClh 11.5

Sequence is:
GClh
PGC
send2cgeo

**Comment by Bananeweizen** [comment] 2015-08-04 05:50
rpoject gc 1.45
lab gpx download 1.1.2
gcvote 3.3
send2 0.32

tampermonkey 3.11

**Comment by Lineflyer** [comment] 2015-10-26 20:35
@Bananeweizen 
What is the sequence of scripts (in which sequence is tampermonkey executing them...which comes first,...)

**Comment by Lineflyer** [comment] 2016-04-14 19:04
Let me close this one. No user complaints and I cannot reproduce this. It might be an issue of the sequence as asked above.

**Closed by Lineflyer** 2016-04-14 19:04 UTC
Labels: Bug
